name: thai_citizen_id
description: Utilities related to Thai Citizen ID
version: 1.2.0
repository: https://github.com/ignitry/thai_citizen_id_dart

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
